/**
 * Primary use case for the team's AI tooling.
 */
export type UseCase = "coding" | "research" | "mixed" | "data" | "writing"

/**
 * Represents a single AI tool the team is currently paying for.
 */
export type ToolContext = {
  tool: string;         // tool name e.g. "cursor", "claude"
  plan: string;         // plan name e.g. "pro", "business"
  seats: number;        // number of users on that tool  
  monthlySpend: number; // what they're actually paying per month for that tool
};

/**
 * Type of recommendation generated by audit rules.
 *
 */
export type Action =
  | "optimal" // optimal  — current setup is fine, no change needed
  | "alternative" // alternative — switch to a different tool entirely
  | "downgrade" // downgrade  — stay on same tool, move to cheaper plan
  | "remove" // remove — drop this tool entirely
  | "consolidate"; // consolidate — reduce number of tools in stack

/**
 * A single actionable recommendation produced by a matched rule.
 */
export type Recommendation = {
  action: Action;           // what kind of change is being suggested
  recommendedTool?: string; // optional, tool to switch to (alternative action)
  recommendedPlan?: string; // optional, plan to switch to (downgrade action)
  reason: string;           // human readable explanation with actual numbers
};

/**
 * A single rule in the audit engine.
 * Rules are domain-aware — the engine itself is not.
 */
export type AuditRule = {
  id: string;                                                  // unique rule identifier e.g. "cursor-business-small-team"
  priority: number;                                            // higher wins when multiple rules match
  condition: (context: AuditParams) => boolean;                // returns true if rule applies to this stack
  calculateSavings: (context: AuditParams) => number;          // returns monthly savings in dollars
  getRecommendation: (context: AuditParams) => Recommendation; // returns what to do
};

/**
 * Input to the audit engine.
 * Represents the user's full AI stack as submitted via the form.
 */
export type AuditParams = {
  useCase:UseCase // what they use it for
  teamSize: number;         // total people on the team
  toolsUsed: ToolContext[]; // every tool they're paying for
};


/**
 * Final output of the audit engine.
 * Consumed by the results page to render savings and recommendations.
 */
export type AuditResult = {
  totalSavings: number;              // sum of savings across all matched rules
  totalAnnualSavings: number;        // totalSavings * 12
  recommendations: Recommendation[]; // all recommendations from matched rules
};